---
title: "第3章 R言語入門 補足"
author: "松浦総一"
format:
  html:
    html-math-method: katex
    theme: sandstone
    toc: true
    toc-expand: 2
    fig-width: 8
    fig-height: 6
editor: visual
pdf-engine: lualatex
execute:
  message : false
  warning: false
---

# R言語入門 補足：データの型

データベースを構築し，分析する前に，必ずデータの型を確認する必要があります。
データの型によって，できることとできないことがあるので，データの型を確認することは重要です。
分析する際によく登場するデータの型には，

- `numeric` 数ベクトル
- `factor` 因子
- `character` 文字列
- `matrix` 行列
- `data.frame` データフレーム
- `list` リスト
- `function` 関数
- `date` 日付
- `tbl` テーブル

がありますが，ここではまず，よく出てくるデータの型として，

- `numeric`
- `facotr`
- `character`
- `date`

を説明します。

## 尺度

データの型を説明する前に，尺度について説明します。
尺度には，大きく分けて

- 名義尺度
- 順序尺度
- 間隔尺度
- 比例尺度

があります。

### 名義尺度

**名義尺度**とは，データの型の一つで，データの値が数値でないものです。例えば，性別や血液型などがあります。
性別のデータとして，1を男性，2を女性として記録しているとしても，女性を2で割っても男性になるわけではなく，ただ記号として1に男性，2に女性を割り当てているにすぎません。このようにデータの値が数値だったとしても，それはカテゴリーのラベルの意味しか持たないのです。このような尺度を**名義尺度**といい，カテゴリー変数(category variable)とも呼ばれます。

### 順序尺度

**順序尺度**とは，データの型の1つで，データの値が数値であっても，大小関係があるものです。
例えば，学生の成績が5,4,3,2,1の5段階であったとします。この場合，5が最も成績が良く，1が最も成績が悪いという大小関係があります。このような尺度を**順序尺度**といいます。
しかし，5は1の5倍良い成績，ということを意味しているわけでない，ということに気をつけましょう。あくまで，数値の大小関係にのみ意味があり，その間の差などには意味がないのです。
たとえば，リカート尺度で測られたアンケート結果などは順序尺度になります。
「どのくらい好きか？」を1から5の5段階で答えるアンケート結果の，4と答えた人と2と答えた人の好きの程度の差は，4の人の方が2の人よりも2倍好きだということを意味しているわけではなく，あくまで4の人の方が2の人よりも好きだということを意味しているだけです。

### 間隔尺度

**間隔尺度**とは，データの型の1つで，データの値が数値であっても，**大小関係があり**，その**間の差にも意味がある**ものです。たとえば気温です。気温が20℃であれば，気温が10℃の時よりも，気温が30℃の時よりも，気温が高いことがわかります。また，気温が20℃の時と40℃の時では，気温の差が20℃であることもわかります。このような尺度を**間隔尺度**といいます。
ただ，間隔尺度は大小関係や差に意味があるものの，比率に意味があるわけではありません。たとえば，気温が20℃の時と40℃の時では，気温が20℃高いことはわかりますが，気温が2倍高いとはいえません。間隔尺度は比率に意味が無いことに注意しましょう。

### 比例尺度

**比例尺度**とは，データの型の1つで，データの値が数値であって，**大小関係があり**，その**間の差にも意味があり**，**比率にも意味がある**ものです。たとえば，体重や価格などがあります。体重が50kgであれば体重が30kgの時よりも体重が重いことがわかり，体重が50kgの時と100kgの時では体重の差が50kgであることもわかり，さらに体重が50kgの時と100kgの時では，体重が2倍重いとも言えます。このような尺度を**比例尺度**といいます。

## 尺度とデータの型

- 名義尺度は，`character`か`factor`
- 順序尺度は，`ordered`か`factor`
- 間隔尺度と比例尺度は，`numeric`

の型が適しています。
それぞれの型を確認してみましょう。

財務データの場合は，
- 各勘定科目の金額は比例尺度なので`numeric`
- 企業名は名義尺度なので`character`か`factor`
- 決算期は順序尺度なので`ordered`か`factor`
-
